version: '3.8'
services:
  reactor:
    build: reactor/reactor
    container_name: reactor   
    environment: 
      - "JAEGER_HOST=jaeger"
    ports:
    - "8080:8080"
    - "9990:9990"
  content:
    build: content/content
    container_name: content    
    environment: 
      - "JAEGER_HOST=jaeger"
    ports:
    - "8081:8080"
    - "9991:9990"
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
    - "6831:6831/udp"
    - "5778:5778"
    - "14268:14268"
    - "16686:16686"